In [3]:
import pandas as pd
import numpy as np

# Creating DataFrames
data = {
    'Name':['Alice','Bob','Charlie','David'],
    'Age':[25,30,35,40],
    'Salary':[50000,60000,70000,8000]
}
df = pd.DataFrame(data)
print(df)

# Reading from CSV
# df = pd.read_csv('data.csv')

# Basic operations
print(df.head(2)) # First 2 rows
print(df.describe()) # Summary statistics
print(df['Age'].mean()) # Average age

# Data Selection
print(df[df['Age'] > 30])
print(df.loc[1:2,['Name','Salary']])

# Handling missing data
df_with_nan = pd.DataFrame({
    'A': [1, 2, np.nan, 4],
    'B': [5, np.nan, np.nan, 8]
})
print(df_with_nan.fillna(value=0)) # Replace NaN with 0
print(df_with_nan.dropna()) # Drop rows with NaN

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000
3    David   40    8000
    Name  Age  Salary
0  Alice   25   50000
1    Bob   30   60000
             Age        Salary
count   4.000000      4.000000
mean   32.500000  47000.000000
std     6.454972  27251.911248
min    25.000000   8000.000000
25%    28.750000  39500.000000
50%    32.500000  55000.000000
75%    36.250000  62500.000000
max    40.000000  70000.000000
32.5
      Name  Age  Salary
2  Charlie   35   70000
3    David   40    8000
      Name  Salary
1      Bob   60000
2  Charlie   70000
     A    B
0  1.0  5.0
1  2.0  0.0
2  0.0  0.0
3  4.0  8.0
     A    B
0  1.0  5.0
3  4.0  8.0


In [2]:
import numpy as np
#creating arrays
arr1 = np.array([1,2,3,4,5]) #1D array
arr2 = np.array([[1,2,3],[4,5,6]]) #2D array

#Array operations (vectorization)
print(arr1 * 2) # Multiply each element by 2
print(arr1 + arr1) # Add arrays element-wise

# Reshaping
arr3 = np.arange(12).reshape(3,4) #Creating a 3x4 array from 0-11
print(arr3)

# Matrix Operations
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])
print(np.dot(matrix1,matrix2)) # Matrix Multiplication

# Statistical operations
data = np.random.normal(0,1,1000) #1000 random numbers from normal distribution
print(f"Mean: {data.mean()}, Std: {data.std()}")


[ 2  4  6  8 10]
[ 2  4  6  8 10]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[19 22]
 [43 50]]
Mean: 0.030272789717925845, Std: 0.99761350795335
